---
title: "Getting and Cleaning Data Proyect"
author: "VeroniqAlecita"
date: "November 2015"
output:
  html_document:
    keep_md: yes
---

## Project Description

The project consist in  create one R script called run_analysis.R and create a github
repository with the description of the script and the data
The goal is to prepare tidy data that can be used for later analysis.

##Study design and data processing

The data is obtained from a link in the course website. Thise represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained: 

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 

Here are the data for the project: 

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip 


###Collection of the raw data
The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details. 


###Notes on the original (raw) data 
For each record it is provided:
======================================

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.

##Creating the tidy datafile

###Guide to create the tidy data file
download an unzip the UCI HAR Dataset AND
In R  set the ".../UCI HAR Dataset" as your working directory
run the run_analysis.R script in R
done!, now the tidy data is a dataset named ExtractedDataMeans

###Cleaning of the data
The data processing consist in the following steps:
Reads the data from the files
- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'features.txt': List of all features.

- 'activity_labels.txt': Links the class labels with their activity name.

- 'train/X_train.txt': Training set.

- 'train/y_train.txt': Training labels.

- 'test/X_test.txt': Test set.

- 'test/y_test.txt': Test labels.

- 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

- 'test/subject_test.txt'

Creates one data table for the train and one for the test data, the X_train data table contains
the data from the X_train, y_train and subject_train files  and the X_test contains the data from 
the X_test, y_test and subject_test files 

Merges the training and the test sets to create one data set.
   using rbindlist from the library "data.table", merges the data tables in a data table 
    named allData by binding the rows

Order the data by subyect and activity class label unsing the arrage command from de dplyr library 


Uses descriptive activity names to name the activities in the data set
  Generates a new variable with the corresponding activity name of the class labels

Extracts only the measurements on the mean and standard deviation for each measurement. 
  using select comand with contains argument from de dplyr library 

Appropriately labels the data set with descriptive variable names. 
  using gsub
  
From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
  Creates a ExtratedDataMeans data table using summarise_each(funs(mean)) and groupe_by  from de dplyr library



##Description of the variables in the tiny_data.txt file
General description of the file including:
 - Dimensions of the dataset: 180 obs. of  68 variables
 - Summary of the data: average of each variable for each activity and each subject.
 - Variables present in the dataset:
 
[1] "subject"                                "activity_label"                        
 [3] "TimeBodyAcceleration-Mean-X"            "TimeBodyAcceleration-Mean-Y"           
 [5] "TimeBodyAcceleration-Mean-Z"            "TimeGravityAcceleration-Mean-X"        
 [7] "TimeGravityAcceleration-Mean-Y"         "TimeGravityAcceleration-Mean-Z"        
 [9] "TimeBodyAccelerationDvDt-Mean-X"        "TimeBodyAccelerationDvDt-Mean-Y"       
[11] "TimeBodyAccelerationDvDt-Mean-Z"        "TimeBodyGyroscope-Mean-X"              
[13] "TimeBodyGyroscope-Mean-Y"               "TimeBodyGyroscope-Mean-Z"              
[15] "TimeBodyGyroscopeDvDt-Mean-X"           "TimeBodyGyroscopeDvDt-Mean-Y"          
[17] "TimeBodyGyroscopeDvDt-Mean-Z"           "TimeBodyAccelerationMagnitude-Mean"    
[19] "TimeGravityAccelerationMagnitude-Mean"  "TimeBodyAccelerationDvDtMagnitude-Mean"
[21] "TimeBodyGyroscopeMagnitude-Mean"        "TimeBodyGyroscopeDvDtMagnitude-Mean"   
[23] "FFTBodyAcceleration-Mean-X"             "FFTBodyAcceleration-Mean-Y"            
[25] "FFTBodyAcceleration-Mean-Z"             "FFTBodyAccelerationDvDt-Mean-X"        
[27] "FFTBodyAccelerationDvDt-Mean-Y"         "FFTBodyAccelerationDvDt-Mean-Z"        
[29] "FFTBodyGyroscope-Mean-X"                "FFTBodyGyroscope-Mean-Y"               
[31] "FFTBodyGyroscope-Mean-Z"                "FFTBodyAccelerationMagnitude-Mean"     
[33] "FFTBodyAccelerationDvDtMagnitude-Mean"  "FFTBodyGyroscopeMagnitude-Mean"        
[35] "FFTBodyGyroscopeDvDtMagnitude-Mean"     "TimeBodyAcceleration-Std-X"            
[37] "TimeBodyAcceleration-Std-Y"             "TimeBodyAcceleration-Std-Z"            
[39] "TimeGravityAcceleration-Std-X"          "TimeGravityAcceleration-Std-Y"         
[41] "TimeGravityAcceleration-Std-Z"          "TimeBodyAccelerationDvDt-Std-X"        
[43] "TimeBodyAccelerationDvDt-Std-Y"         "TimeBodyAccelerationDvDt-Std-Z"        
[45] "TimeBodyGyroscope-Std-X"                "TimeBodyGyroscope-Std-Y"               
[47] "TimeBodyGyroscope-Std-Z"                "TimeBodyGyroscopeDvDt-Std-X"           
[49] "TimeBodyGyroscopeDvDt-Std-Y"            "TimeBodyGyroscopeDvDt-Std-Z"           
[51] "TimeBodyAccelerationMagnitude-Std"      "TimeGravityAccelerationMagnitude-Std"  
[53] "TimeBodyAccelerationDvDtMagnitude-Std"  "TimeBodyGyroscopeMagnitude-Std"        
[55] "TimeBodyGyroscopeDvDtMagnitude-Std"     "FFTBodyAcceleration-Std-X"             
[57] "FFTBodyAcceleration-Std-Y"              "FFTBodyAcceleration-Std-Z"             
[59] "FFTBodyAccelerationDvDt-Std-X"          "FFTBodyAccelerationDvDt-Std-Y"         
[61] "FFTBodyAccelerationDvDt-Std-Z"          "FFTBodyGyroscope-Std-X"                
[63] "FFTBodyGyroscope-Std-Y"                 "FFTBodyGyroscope-Std-Z"                
[65] "FFTBodyAccelerationMagnitude-Std"       "FFTBodyAccelerationDvDtMagnitude-Std"  
[67] "FFTBodyGyroscopeMagnitude-Std"          "FFTBodyGyroscopeDvDtMagnitude-Std" 

#Aditional information about the variables

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (Time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (TimeBodyAccelerometer-XYZ and TimeBodyGyroscope-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain DvDt signals (TimeBodyAccelerationDvDt-XYZ and TimeBodyGyroscopeDvDt-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (TimeBodyAccelerationMagnitude, TimeGravityAccelerationMagnitude, TimeBodyAccelerattionDvDtMagnitude, TimeBodyGyroscopeMagnitude, TimeBodyGyroscopeDvDtMagnitude). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing FFTBodyAcceleration-XYZ, FFTBodyAccelerationDvDt-XYZ, FFTBodyGyroscope-XYZ, FFTBodyAcceleratioDvDtMagnitude, FFTBodyGyroscopeMagnitude, FFTBodyGyroscopeDvDtMagnitude. (Note the 'FFT' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.


The set of variables that were estimated from these signals are: 

Mean: Mean value
Std: Standard deviation


##Sources
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 

data from:

==================================================================
Human Activity Recognition Using Smartphones Dataset
Version 1.0
==================================================================
Jorge L. Reyes-Ortiz, Davide Anguita, Alessandro Ghio, Luca Oneto.
Smartlab - Non Linear Complex Systems Laboratory
DITEN - Università degli Studi di Genova.
Via Opera Pia 11A, I-16145, Genoa, Italy.
activityrecognition@smartlab.ws
www.smartlab.ws
==================================================================
